import React from 'react';
import { Text, Platform, StyleSheet } from 'react-native';

export const FONT = Platform.select({ ios: 'System', web: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", sans-serif', default: 'System' });

export const DEL_W = 88;

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F2F2F7' },
  container: { flex: 1, width: '100%', maxWidth: 520, alignSelf: 'center' },
  largeTitle: { fontFamily: FONT, fontSize: 34, fontWeight: '700', color: '#000', marginBottom: 12, marginTop: 8 },
  sectionTitle: { fontFamily: FONT, fontSize: 13, color: '#6C6C70', textTransform: 'uppercase', marginTop: 20, marginBottom: 6, marginLeft: 16 },
  card: { backgroundColor: '#fff', borderRadius: 12, marginTop: 12, overflow: 'hidden', padding: 0 },
  row: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 16 },
  sep: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#C6C6C8' },
  body: { fontFamily: FONT, fontSize: 17, color: '#000' },
  caption: { fontFamily: FONT, fontSize: 13, color: '#6C6C70', paddingHorizontal: 16, marginTop: 4 },
  hint: { fontFamily: FONT, fontSize: 15, color: '#6C6C70', textAlign: 'center', marginTop: 16 },
  limitInput: { fontFamily: FONT, fontSize: 17, textAlign: 'right', width: 120, color: '#007AFF' },
  cols: { flexDirection: 'row', alignItems: 'flex-start', gap: 24 },
  col: { flex: 1, minWidth: 0 },
  boxHead: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  big3: { fontFamily: FONT, fontSize: 28, fontWeight: '700', marginTop: 2 },
  dateRow: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 4, paddingTop: 10 },
  dateText: { fontFamily: FONT, fontSize: 13, color: '#6C6C70' },
  paceHead: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  paceRow: { paddingHorizontal: 0, marginTop: 8, justifyContent: 'space-between' },
  searchRow: { flexDirection: 'row', alignItems: 'center' },
  searchInput: { flex: 1, minWidth: 200, marginTop: 0, backgroundColor: '#E3E3E8' },
  filterBtn: { paddingLeft: 14, paddingVertical: 10 },
  filterRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 12 },
  filterSeg: { marginTop: 0, width: 250 },
  chipsRow: { flexDirection: 'row', flexWrap: 'wrap' },
  shellWide: { flex: 1, flexDirection: 'row', width: '100%' },
  contentWide: { padding: 32, paddingBottom: 60, maxWidth: 1180, width: '100%', alignSelf: 'center' },
  sidebar: { width: 240, backgroundColor: '#fff', borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: '#C6C6C8', paddingHorizontal: 16, paddingTop: 32, paddingBottom: 20 },
  brand: { fontFamily: FONT, fontSize: 24, fontWeight: '700', marginBottom: 20, paddingHorizontal: 8 },
  addBtn: { backgroundColor: '#007AFF', borderRadius: 10, paddingVertical: 12, alignItems: 'center', marginBottom: 16 },
  addBtnText: { fontFamily: FONT, color: '#fff', fontSize: 15, fontWeight: '600' },
  navItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 12, borderRadius: 10, marginBottom: 2 },
  navActive: { backgroundColor: '#EAF2FF' },
  navText: { fontFamily: FONT, fontSize: 16, color: '#000' },
  big2: { fontFamily: FONT, fontSize: 34, fontWeight: '700' },
  big: { fontFamily: FONT, fontSize: 40, fontWeight: '700', paddingHorizontal: 16, marginTop: 4 },
  donutCenter: { fontFamily: FONT, fontSize: 17, fontWeight: '600' },
  barBg: { height: 8, borderRadius: 4, backgroundColor: '#E5E5EA' },
  seg: { flexDirection: 'row', backgroundColor: '#E3E3E8', borderRadius: 9, padding: 2, marginTop: 12 },
  segItem: { flex: 1, paddingVertical: 7, alignItems: 'center', borderRadius: 7 },
  segActive: { backgroundColor: '#fff', shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 3, shadowOffset: { width: 0, height: 1 } },
  segText: { fontFamily: FONT, fontSize: 13 },
  input: { fontFamily: FONT, fontSize: 17, backgroundColor: '#F2F2F7', borderRadius: 10, padding: 12, marginTop: 10 },
  button: { backgroundColor: '#007AFF', borderRadius: 12, padding: 14, alignItems: 'center', marginTop: 14 },
  buttonText: { fontFamily: FONT, color: '#fff', fontSize: 17, fontWeight: '600' },
  link: { fontFamily: FONT, color: '#007AFF', fontSize: 17 },
  fab: { position: 'absolute', right: 20, bottom: 84, width: 56, height: 56, borderRadius: 28, backgroundColor: '#007AFF', alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 8, shadowOffset: { width: 0, height: 4 } },
  fabText: { color: '#fff', fontSize: 32, marginTop: -2 },
  tabbar: { position: 'absolute', bottom: 0, left: 0, right: 0, flexDirection: 'row', backgroundColor: 'rgba(249,249,249,0.96)', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#C6C6C8', paddingBottom: 16, paddingTop: 6 },
  tab: { flex: 1, alignItems: 'center' },
  tabLabel: { fontFamily: FONT, fontSize: 10, color: '#8E8E93', marginTop: 2 },
  sheetWrap: { flex: 1, backgroundColor: 'rgba(0,0,0,0.3)' },
  sheet: { backgroundColor: '#fff', borderBottomLeftRadius: 20, borderBottomRightRadius: 20, padding: 20, paddingBottom: 16, maxHeight: '64%', width: '100%', maxWidth: 520, alignSelf: 'center' },
  amountInput: { fontFamily: FONT, fontSize: 40, fontWeight: '700', textAlign: 'center', marginVertical: 10 },
  dayChip: { flex: 1, backgroundColor: '#F2F2F7', borderRadius: 14, paddingVertical: 8, marginHorizontal: 2, alignItems: 'center' },
  stepper: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 8, paddingHorizontal: 4 },
  stepBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#F2F2F7', alignItems: 'center', justifyContent: 'center' },
  stepText: { fontFamily: FONT, fontSize: 20, color: '#007AFF' },
  delBg: { position: 'absolute', right: 0, top: 0, bottom: 0, width: DEL_W, backgroundColor: '#FF3B30' },
  delBtn: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  delText: { fontFamily: FONT, color: '#fff', fontSize: 17, fontWeight: '600' },
  chip: { backgroundColor: '#F2F2F7', borderRadius: 18, paddingVertical: 8, paddingHorizontal: 12, margin: 4 },
  chipText: { fontFamily: FONT, fontSize: 15 },
});
